config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"

  resources :quotes, only: [], path: '' do
    collection { get 'quote', to: "quotes#quote"}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index; end

  def quote
    @random_quote = CsvParser.call(File.read(Rails.root.join('public', 'csv', 'quotes.csv'))).sample

    respond_to do |format|
      format.html {}
      format.json { render json: { data: @random_quote, success: true }, status: :ok }
      format.xml { render xml: @random_quote }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'partials/header' %>
    <%= yield %>
    <%= render partial: 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="bg-light text-center text-lg-start" style="width:100%; position: absolute; bottom: 0">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © <%= Time.new.year %> Copyright:
    <a class="text-dark" href="https://www.houzz.com/">Houzz</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-2" style="background-color: rgba(0, 0, 0, 0.2);">
  <a class="navbar-brand" href="/">Quote</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/quotes/index.html.erb
<div class="container-fluid mt-4">
  <h1>Welcome to the world of quotes.</h1>
  <button type="button" class="btn btn-info"><%= link_to 'Random Quote(HTML)', quote_quotes_path %></button>
  <button type="button" class="btn btn-info"><%= link_to 'Random Quote(JSON)', quote_quotes_path(format: :json) %></button>
  <button type="button" class="btn btn-info"><%= link_to 'Random Quote(XML)', quote_quotes_path(format: :xml) %></button>
</div>

app/views/quotes/quote.html.erb
<% title = @random_quote['title'] %>
<% author = @random_quote['author'] %>

<div class="mt-4 p-5 bg-secondary text-white rounded center" style="width: 80%; margin: 0 auto;">
  <p>Thought of the day</p>
  <h1><%= title %></h1>
  <p>By <%= author.titleize %></p>
</div>